const cloud = [
  { text: "PHP", value: 20 },
  { text: "Laravel", value: 15 },
  { text: "Lumen", value: 10 },
  { text: "Ruby On Rails", value: 10 },
  { text: "MySQL", value: 7 },
  { text: "MS SQL Server", value: 5 },
  { text: "Postgres", value: 7 },
  { text: "mongoDB", value: 6 },
  { text: "React", value: 12 },
  { text: "Redux", value: 7 },
  { text: "Algolia", value: 5 },
  { text: "Node.js", value: 7 },
  { text: "Sails.js", value: 7 },
  { text: "HTML", value: 9 },
  { text: "XML", value: 5 },
  { text: "Xpath", value: 5 },
  { text: "CSS", value: 8 },
  { text: "LESS", value: 8 },
  { text: "SASS", value: 8 },
  { text: "AJAX ", value: 3 },
  { text: "API ", value: 4 },
  { text: "REST ", value: 4 },
  { text: "SOAP ", value: 4 },
  { text: "Javascript ", value: 8 },
  { text: "jQuery ", value: 4 },
  { text: "Pug/Jade ", value: 4 },
  { text: "HAML ", value: 4 },
  { text: "Foundation ", value: 4 },
  { text: "Bootstrap ", value: 5 },
  { text: "Git", value: 10 },
  { text: "SFTP", value: 2 },
  { text: "FTP", value: 2 },
  { text: "Bower", value: 2.5 },
  { text: "Gulp", value: 2.5 },
  { text: "Webpack", value: 2.5 },
  { text: "Yarn", value: 2.5 },
  { text: "NPM", value: 2.5 },
  { text: "AWS", value: 8 },
  { text: "Heroku", value: 6 },
  { text: "LAMP", value: 8 },
  { text: "Drupal", value: 9 },
  { text: "Wordpress", value: 9 },
  { text: "MS-DOS", value: 6 },
  { text: "Windows", value: 6 },
  { text: "Linux", value: 6 },
  { text: "Mac OS", value: 6 },
  { text: "Raspberry PI", value: 5 },
  { text: "SSH", value: 6 },
  { text: "CRON", value: 6 },
  { text: "Bash", value: 6 },
  { text: "Nginx", value: 6 },
  { text: "Apache", value: 6 },
  { text: "IIS", value: 5 },
  { text: "Varnish", value: 5 },
  { text: "Memcache", value: 5 },
  { text: "Redis", value: 5 },
  { text: "VM Ware", value: 5 },
  { text: "VirtualBox", value: 5 },
  { text: "Vagrant", value: 5 },
  { text: "PhotoShop", value: 3 },
  { text: "Illustrator", value: 3 },
  { text: "Ableton Live", value: 3 },
]

export default cloud
